name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run basic check
        run: |
          python -c "import pandas, numpy, sklearn, mlflow"

      - name: Run MLflow training
        run: |
          python - <<EOF
          import pandas as pd
          from sklearn.model_selection import train_test_split
          from sklearn.ensemble import RandomForestClassifier
          import numpy as np
          import mlflow
          import mlflow.sklearn

          # Set MLflow tracking directory
          mlflow.set_tracking_uri("file://$(pwd)/mlruns")
          mlflow.set_experiment("Fitness Experiment")

          # Load data
          df = pd.read_csv("preprocessing/data_fitness_processed.csv")
          X = df.drop(columns=['is_fit'])
          y = df['is_fit']

          # Ambil kolom numerik saja
          X = X.select_dtypes(include=[np.number])

          # Split data
          X_train, X_test, y_train, y_test = train_test_split(
              X, y, test_size=0.2, random_state=42
          )

          # Aktifkan autologging
          mlflow.sklearn.autolog()

          with mlflow.start_run(run_name="training"):
              model = RandomForestClassifier(
                  n_estimators=100,
                  random_state=42
              )
              model.fit(X_train, y_train)
          EOF
